<?php

use App\Models\MasterFiles\Inventory\Item;
use App\Models\Modules\ItemMovement;
use Faker\Factory;
use Illuminate\Database\Seeder;

class InitialInventorySeeder extends Seeder {

    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run() {
        $movements = [];

        $possibleWarehouses = [
            "W_QC1", "W_QC2", "W_QC3", "W_QC4"
        ];

        $possibleItems = Item::ItemTypeCode("PRM")->get()->toArray();

        $possibleCosts = [
            20, 25, 15, 18, 22
        ];

        for ($i = 0; $i < 30; $i ++) {
            $faker = Factory::create();

            $item     = $possibleItems[$faker->randomKey($possibleItems)];
            $movement = [
                "movement_date" => $faker->dateTimeBetween('-1 years', 'now'),
                "ref_doc_type"  => "PO",
                "ref_doc_no"    => "PO-" . str_pad("" . ($i + 1), 7, "0", STR_PAD_LEFT),
                "company_code"  => "HYTORC",
                "location_code" => $possibleWarehouses[$faker->randomKey($possibleWarehouses)],
                "item_type"     => "PRM", //plastics
                "item_code"     => $item["code"],
                "item_name"     => $item["name"],
                "item_uom_code" => "pc",
                "qty"           => $faker->randomNumber(2),
                "unit_cost"     => $possibleCosts[$faker->randomKey($possibleCosts)],
                "remarks"       => "Item movement auto generated by system for testing. DO NOT USE IN PRODUCTION!",
                "status"        => "Open"
            ];

            array_push($movements, $movement);
        }

        ItemMovement::insert($movements);

        //  Post all movements
        $savedMovements = ItemMovement::all();
        foreach ($savedMovements AS $movement) {
            echo "\nPosting {$movement->id} - {$movement->ref_doc_no}";
            $movement->post();
        }
    }

}
